### ISSUE TITLE
State of this project

### ISSUE THREAD

**Issue by bootandy** [dtheodor/flask-sqlalchemy-session#10]
Is this project abandoned? 

I happened to come across this and it looks like something I want to use. 

Can we remove the python 2.6 stuff and add python 3.X builds to the CI instead? Are you still accepting PRs?

head build is red currently.

**Comment by dtheodor** [comment]
I haven't maintained this in a while. The project is very small so it should barely need maintenance, unless some breaking API change takes place in the libraries it depends on. PRs welcome.
