### ISSUE TITLE
Multiple Databases?

### ISSUE THREAD

**Issue by npcole** [dtheodor/flask-sqlalchemy-session#4]
Can flask-sql-alchemy-session be used with multiple databases, or is it designed only for use with a single database?

Is there anything like: http://flask-appbuilder.readthedocs.org/en/latest/multipledbs.html

If so, could some documentation about how to do it be added?

**Comment by dtheodor** [comment]
You can use the technique of mapping different tables to different databases (aka vertical paritioning) as described in SQLA docs at [Partitioning Strategies](http://docs.sqlalchemy.org/en/rel_1_0/orm/persistence_techniques.html?highlight=partitioning#partitioning-strategies) and [binds API](http://docs.sqlalchemy.org/en/rel_1_0/orm/session_api.html#sqlalchemy.orm.session.Session.params.binds).

flask-sqlalchemy-session is external to this configuration. If I take the example from the link you posted, you would do

``` python
#engines
default_engine = create_engine(db_uri)
engine1 = create_engine(db_uri1)
engine2 = create_engine(db_uri2)
# configure your mappings
session_factory = sessionmaker(
    bind=default_engine,
    binds={
        Model1: engine1,
        Model2: engine2
    }
)
# setup Flask app
app = Flask()
session = flask_scoped_session(session_factory, app)
```

**Comment by npcole** [comment]
Thank you, that's really helpful.
