### ISSUE TITLE
What about session.close() ?

### ISSUE THREAD

**Issue by thanoskrg** [dtheodor/flask-sqlalchemy-session#6]
I would like to ask if it is necessary to perform `session.close()` each time I use **`current_session`** ?
For one user (basically me) during development everything works fine. But hat happens if we go in production and every user uses this `current_session` object ? What about the max pool of connections in my database ? 

I am sorry for asking, but I cant find any clear explanation through the SQLAlchemy docs. 

Thanks in advance.

**Comment by dtheodor** [comment]
http://docs.sqlalchemy.org/en/latest/orm/contextual.html#sqlalchemy.orm.scoping.scoped_session.remove 

This is called at the end of each request's lifetime, which does what you want. This `current_session` object is not really a single object, it's an API (in the form of a single object) that provides a different session for each request.

Each request will use (and at the end of it release) a connection from the pool, it's up to you to configure the pool size for each of your webserver processes (http://docs.sqlalchemy.org/en/latest/core/pooling.html), taking into account your database's capability to accept simultaneous connections.

If you are really worried about your production db's connection pool you should use a connection pool system specific for your database (https://wiki.postgresql.org/wiki/PgBouncer for Postgres)

**Comment by thanoskrg** [comment]
Thank you for your immediate response!
The reason why I was worried about closing the connection at the end of each request, is because pgAdmin Server Status utility keeps listing one connection from my python application. 
Although this connection is listed as an _idle_ one.

Thank you for your nice project which is so helpful and greetings from Greece
