### ISSUE TITLE
Skip session creation?

### ISSUE THREAD

**Issue by Chris2048** [dtheodor/flask-sqlalchemy-session#9]
Hi, Is there a way to easily skip session creation for an endpoint? I have an EP that doesn't use SQL but *is* frequently polled so it creates a session each time.

**Comment by dtheodor** [comment]
Can you give some details in what you're seeing, how do you see that the session is being created? [SQL Alchemy scoped session](https://docs.sqlalchemy.org/en/13/orm/contextual.html) lazily initializes a session per request so it should not be creating anything unless you're explicitly accessing the session object

**Comment by Chris2048** [comment]
Ah, I believe I see this now. I describe a few of my conclusions [here](https://github.com/pymssql/pymssql/issues/460), of interest to this project might be the modification to make connections per-request also.
